### PR TITLE
Aishwarya - Added words for 7 to 11

### PR DESCRIPTION
**Pull request by aishwaryanair04**
I have added 5 words to fill up brackets numbered from 7 to 11

### CODE REVIEW

**Review by shabhishek98 — CHANGES_REQUESTED** [review]
Please add madlib file as well.

**Comment by Prachi-0030** [comment]
Yeah, first the madlibs needs to be edited and from that the story will come, so 2 files in total should be present when requesting a pull.

**Comment by aishwaryanair04** [comment]
Added values to madlibs_list file

**Review by kanak9424 — APPROVED** [review]
Great choice of words especially hydrochloric acid for liquid.

**Review by Prachi-0030 — APPROVED** [review]
On submitting the changes, please make sure both the files are there

**Pull request merged**
